package cmd

import (
	"fmt"

	helper "github.com/home-assistant/cli/client"
	log "github.com/sirupsen/logrus"
	"github.com/spf13/cobra"
)

var addonsLogsCmd = &cobra.Command{
	Use:     "logs [slug]",
	Aliases: []string{"log", "lg"},
	Short:   "View the log output of a running Home Assistant add-on",
	Long: `
Allowing you to look at the log output generated by a Home Assistant add-on.
`,
	Example: `
  ha addons logs core_ssh
`,
	ValidArgsFunction: addonsCompletions,
	Args:              cobra.ExactArgs(1),
	Run: func(cmd *cobra.Command, args []string) {
		log.WithField("args", args).Debug("addons logs")

		section := "addons/{slug}"

		request, err := processLogsFlags(section, cmd)

		if err != nil {
			fmt.Printf("Error: %v", err)
			ExitWithError = true
			return
		}

		slug := args[0]
		request.SetPathParam("slug", slug)

		resp, err := request.Send()

		if err != nil {
			fmt.Println(err)
			ExitWithError = true
			return
		}

		ExitWithError = !helper.StreamTextResponse(resp)
	},
}

func init() {
	addLogsFlags(addonsLogsCmd)

	addonsCmd.AddCommand(addonsLogsCmd)
}
