package cmd

import (
	helper "github.com/home-assistant/cli/client"
	log "github.com/sirupsen/logrus"
	"github.com/spf13/cobra"
)

var appsLogsCmd = &cobra.Command{
	Use:     "logs [slug]",
	Aliases: []string{"log", "lg"},
	Short:   "View the log output of a running Home Assistant app",
	Long: `
Allowing you to look at the log output generated by a Home Assistant app.
`,
	Example: `
  ha apps logs core_ssh
`,
	ValidArgsFunction: appsCompletions,
	Args:              cobra.ExactArgs(1),
	Run: func(cmd *cobra.Command, args []string) {
		log.WithField("args", args).Debug("apps logs")

		section := "addons/{slug}"

		request, err := processLogsFlags(section, cmd)

		if err != nil {
			helper.PrintError(err)
			ExitWithError = true
			return
		}

		slug := args[0]
		request.SetPathParam("slug", slug)

		resp, err := request.Send()

		if err != nil {
			helper.PrintError(err)
			ExitWithError = true
			return
		}

		ExitWithError = !helper.StreamTextResponse(resp)
	},
}

func init() {
	addLogsFlags(appsLogsCmd)

	appsCmd.AddCommand(appsLogsCmd)
}
