package cmd

import (
	"fmt"

	helper "github.com/home-assistant/cli/client"
	log "github.com/sirupsen/logrus"
	"github.com/spf13/cobra"
)

var audioLogsCmd = &cobra.Command{
	Use:     "logs",
	Aliases: []string{"log", "lg"},
	Short:   "View the log output of Home Assistant Audio",
	Long: `
Allowing you to look at the log output generated by the Home Assistant Audio
running on your Home Assistant system.`,
	Example: `
  ha audio logs`,
	ValidArgsFunction: cobra.NoFileCompletions,
	Args:              cobra.NoArgs,
	Run: func(cmd *cobra.Command, args []string) {
		log.WithField("args", args).Debug("audio logs")

		section := "audio"

		request, err := processLogsFlags(section, cmd)

		if err != nil {
			fmt.Printf("Error: %v", err)
			ExitWithError = true
			return
		}

		resp, err := request.Send()

		if err != nil {
			helper.PrintError(err)
			ExitWithError = true
			return
		}

		ExitWithError = !helper.StreamTextResponse(resp)
	},
}

func init() {
	addLogsFlags(audioLogsCmd)

	audioCmd.AddCommand(audioLogsCmd)
}
