package cmd

import (
	helper "github.com/home-assistant/cli/client"
	log "github.com/sirupsen/logrus"
	"github.com/spf13/cobra"
)

var coreLogsCmd = &cobra.Command{
	Use:     "logs",
	Aliases: []string{"log", "lg"},
	Short:   "View the log output of Home Assistant Core",
	Long: `
Allowing you to look at the log output generated by the Home Assistant Core
running on your Home Assistant system.`,
	Example: `
  ha core logs`,
	ValidArgsFunction: cobra.NoFileCompletions,
	Args:              cobra.NoArgs,
	Run: func(cmd *cobra.Command, args []string) {
		log.WithField("args", args).Debug("core logs")

		section := "core"

		request, err := processLogsFlags(section, cmd)

		if err != nil {
			helper.PrintError(err)
			ExitWithError = true
			return
		}

		resp, err := request.Send()

		if err != nil {
			helper.PrintError(err)
			ExitWithError = true
			return
		}

		ExitWithError = !helper.StreamTextResponse(resp)
	},
}

func init() {
	addLogsFlags(coreLogsCmd)

	coreCmd.AddCommand(coreLogsCmd)
}
