package cmd

import (
	helper "github.com/home-assistant/cli/client"
	log "github.com/sirupsen/logrus"
	"github.com/spf13/cobra"
)

var multicastLogsCmd = &cobra.Command{
	Use:     "logs",
	Aliases: []string{"log", "lg"},
	Short:   "View the log output of the Home Assistant Multicast server",
	Long: `
Allowing you to look at the log output generated by the Home Assistant Multicast server.
`,
	Example: `
  ha multicast logs
`,
	ValidArgsFunction: cobra.NoFileCompletions,
	Args:              cobra.NoArgs,
	Run: func(cmd *cobra.Command, args []string) {
		log.WithField("args", args).Debug("multicast logs")

		section := "multicast"

		request, err := processLogsFlags(section, cmd)

		if err != nil {
			helper.PrintError(err)
			ExitWithError = true
			return
		}

		resp, err := request.Send()

		if err != nil {
			helper.PrintError(err)
			ExitWithError = true
			return
		}

		ExitWithError = !helper.StreamTextResponse(resp)
	},
}

func init() {
	addLogsFlags(multicastLogsCmd)

	multicastCmd.AddCommand(multicastLogsCmd)
}
